##################################################################
## 
##      Configuración del módulo de lectura de base de datos   
##      
##################################################################

Servidor:
    IP: 138.4.46.69
    Puerto: 49172
    
BBDD:
    Nombre: MeteoStation4k    
    Usuario: Geonica
    Contrasena: g30n1c4
    Database: GEONICASUITE4  K
